language: node_js
node_js:
  - "stable"
services: mongodb
# text search is experimental in mongodb 2.4 -> use mongodb 3.2
# https://www.mongodb.com/blog/post/mongodb-text-search-experimental-feature-in
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
